### ISSUE TITLE
png without V8?

### ISSUE THREAD

**Issue by vnijs** [rich-iannone/DiagrammeRsvg#1]
Just curious ... is a conversion from mermaid svg to png possible without V8 at this time?

**Comment by timelyportfolio** [comment]
Should be possible with the new `webshot`, which doesn't require `V8` but does require `phantom.js`.  Would this be an option?

**Comment by vnijs** [comment]
I don't think so unfortunately. I posted https://github.com/wch/webshot/issues/20: "Ideally, I'd like to press a button to take a screenshot of the current page in a shiny app, store the image, and then put a reference to the screenshot into an knitr document in the app or into Rstudio." but @wch suggested this won't work.

Also, I just noticed that you cannot get htmlwidgets into a PDF or Word document from Rstudio at all. Converting to PNG inside knitr / rmarkdown would be really nice. I was hoping that maybe something like https://github.com/jeroenooms/rsvg could be used somehow?

cc: @ramnathv

**Comment by ramnathv** [comment]
I think @yihui was working on something to this effect that will allow screenshots of htmlwidgets in rmd documents that are converted to pdf.

**Comment by yihui** [comment]
It has been done. You just need the dev version of knitr. See https://bookdown.org/yihui/bookdown/html-widgets.html

**Comment by vnijs** [comment]
Thanks @yihui. Rendering of DiagrammeR plots in HTML, Word, and PDF from Rstudio works. Nice!

The issue I posted earlier on the webshot github repot was about taking a screen shot of the page I'm looking at in my browser. I guess for that you would need something like: https://github.com/niklasvh/html2canvas
