### ISSUE TITLE
why a seperate library?

### ISSUE THREAD

**Issue by HJAllen** [rich-iannone/DiagrammeRsvg#4]
Not an issue but just a question. why not include export_svg in the DiagrammeR library? Might cut down on confusion of needing a separate library for that functionality.

**Comment by rich-iannone** [comment]
It wasn't allowed by a CRAN maintainer because it relied on the `V8` library which is thought to be difficult to install/build on some platforms. It originally was part of DiagrammeR.

**Comment by HJAllen** [comment]
i see. thanks.
